runtime: python27
api_version: 1
service: teta-develop
threadsafe: true

handlers:
  - url: /
    static_files: index.html
    upload: index\.html
    secure: always

  - url: /(.*)
    static_files: \1
    upload: (.*)
    secure: always